=== GeoKnow/GeoKnowGeneratorUI/target/generator/uploads/limes.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT LIMES (PREFIX*, SOURCE, TARGET, METRIC, ACCEPTANCE, REVIEW, EXECUTION*, GRANULARITY*, OUTPUT*)>
<!ELEMENT PREFIX (NAMESPACE, LABEL)>
<!ELEMENT NAMESPACE (#PCDATA)>
<!ELEMENT LABEL (#PCDATA)>
<!ELEMENT SOURCE (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, RESTRICTION+, PROPERTY+, TYPE*)>
<!ELEMENT TARGET (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, RESTRICTION+, PROPERTY+, TYPE*)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT RESTRICTION (#PCDATA)>
<!ELEMENT METRIC (#PCDATA)>
<!ELEMENT ACCEPTANCE (THRESHOLD, FILE, RELATION)>
<!ELEMENT REVIEW (THRESHOLD, FILE, RELATION)>
<!ELEMENT RELATION (#PCDATA)>
<!ELEMENT ENDPOINT (#PCDATA)>
<!ELEMENT GRAPH (#PCDATA)>
<!ELEMENT VAR (#PCDATA)>
<!ELEMENT CLASS (#PCDATA)>
<!ELEMENT PROPERTY (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT THRESHOLD (#PCDATA)>
<!ELEMENT FILE (#PCDATA)>
<!ELEMENT PAGESIZE (#PCDATA)>
<!ELEMENT EXECUTION (#PCDATA)>
<!ELEMENT GRANULARITY (#PCDATA)>
<!ELEMENT OUTPUT (#PCDATA)>

=== GeoKnow/GeoKnowGeneratorUI/src/main/webapp/data/limes-config-files/dbpedia-dbpedia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
		<LABEL>foaf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/</NAMESPACE>
		<LABEL>drugbank</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www4.wiwiss.fu-berlin.de/sider/resource/sider/</NAMESPACE>
		<LABEL>sider</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://dbpedia.org/ontology/</NAMESPACE>
		<LABEL>dbpedia</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://dbpedia.org/property/</NAMESPACE>
		<LABEL>dbpedia-p</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://purl.org/dc/terms/</NAMESPACE>
		<LABEL>dc</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/</NAMESPACE>
		<LABEL>diseasome</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>dbpedia</ID>
		<ENDPOINT>http://dbpedia.org/sparql</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type dbpedia:Drug</RESTRICTION>
		<PROPERTY>rdfs:label AS nolang->lowercase</PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>dbpedia</ID>
		<ENDPOINT>http://dbpedia.org/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type dbpedia:Drug</RESTRICTION>
		<PROPERTY>rdfs:label AS nolang->lowercase RENAME name</PROPERTY>
	</TARGET>
	<METRIC>trigrams(x.rdfs:label,y.name)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.8</THRESHOLD>
		<FILE>dbpedia_dbpedia_duplicates.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>dbpedia_dbpedia_reviewme.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>Simple</EXECUTION>
	<OUTPUT>TTL</OUTPUT>
</LIMES>

=== GeoKnow/GeoKnowGeneratorUI/src/main/webapp/data/limes-config-files/dblp-semanticwebresearcher.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
      <LABEL>rdf</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
      <LABEL>owl</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
      <LABEL>foaf</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
      <LABEL>rdfs</LABEL>
   </PREFIX>
   <SOURCE>
      <ID>datasemanticweborg</ID>
      <ENDPOINT>http://data.semanticweb.org/sparql</ENDPOINT>
      <VAR>?a</VAR>
      <PAGESIZE>-1</PAGESIZE>
      <RESTRICTION>?a rdf:type foaf:Person</RESTRICTION>
      <PROPERTY>foaf:name AS lowercase</PROPERTY>
   </SOURCE>
   <TARGET>
      <ID>DBLP</ID>
      <ENDPOINT>http://dblp.l3s.de/d2r/sparql</ENDPOINT>
      <VAR>?b</VAR>
      <PAGESIZE>1000</PAGESIZE>
      <RESTRICTION>?b rdf:type foaf:Agent</RESTRICTION>
      <PROPERTY>foaf:name AS lowercase</PROPERTY>
   </TARGET>
   <METRIC>trigrams(a.foaf:name, b.foaf:name)</METRIC>
   <ACCEPTANCE>
      <THRESHOLD>0.7</THRESHOLD>
      <FILE>accept.nt</FILE>
      <RELATION>owl:sameAs</RELATION>
   </ACCEPTANCE>
   <REVIEW>
      <THRESHOLD>0.7</THRESHOLD>
      <FILE>review.nt</FILE>
      <RELATION>owl:sameAs</RELATION>
   </REVIEW>
   <EXECUTION>Simple</EXECUTION>
   <OUTPUT>TAB</OUTPUT>
</LIMES>

=== GeoKnow/GeoKnowGeneratorUI/src/main/webapp/data/limes-config-files/dbpedia-actors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://dbpedia.org/ontology/</NAMESPACE>
		<LABEL>dbpedia</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>dbpedia</ID>
		<ENDPOINT>http://dbpedia.org/sparql</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type dbpedia:Actor</RESTRICTION>
		<PROPERTY>rdfs:label AS nolang->lowercase</PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>dbpedia</ID>
		<ENDPOINT>http://dbpedia.org/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type dbpedia:Actor</RESTRICTION>
		<PROPERTY>rdfs:label AS nolang->lowercase RENAME name</PROPERTY>
	</TARGET>
	<METRIC>jaro(x.rdfs:label,y.name)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.9</THRESHOLD>
		<FILE>dbpedia_actors_duplicates.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.8</THRESHOLD>
		<FILE>dbpedia_actors_reviewme.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>Simple</EXECUTION>
	<OUTPUT>TTL</OUTPUT>
</LIMES>

=== GeoKnow/GeoKnowGeneratorUI/src/main/webapp/data/limes-config-files/lgd-lgd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://geovocab.org/geometry#</NAMESPACE>
		<LABEL>geom</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.opengis.net/ont/geosparql#</NAMESPACE>
		<LABEL>geos</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://linkedgeodata.org/ontology/</NAMESPACE>
		<LABEL>lgdo</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>linkedgeodata</ID>
		<ENDPOINT>http://linkedgeodata.org/sparql</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>2000</PAGESIZE>
		<RESTRICTION>?x a lgdo:RelayBox</RESTRICTION>
		<PROPERTY>geom:geometry/geos:asWKT RENAME polygon</PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>linkedgeodata</ID>
		<ENDPOINT>http://linkedgeodata.org/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>2000</PAGESIZE>
		<RESTRICTION>?y a lgdo:RelayBox</RESTRICTION>
		<PROPERTY>geom:geometry/geos:asWKT RENAME polygon</PROPERTY>
	</TARGET>
	<METRIC>hausdorff(x.polygon, y.polygon)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.9</THRESHOLD>
		<FILE>lgd_relaybox_verynear.nt</FILE>
		<RELATION>lgdo:near</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>lgd_relaybox_near.nt</FILE>
		<RELATION>lgdo:near</RELATION>
	</REVIEW>
	<EXECUTION>Simple</EXECUTION>
	<OUTPUT>TAB</OUTPUT>
</LIMES>

=== GeoKnow/GeoKnowGeneratorUI/src/main/webapp/data/limes-config-files/europeana-deduplication.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES
  SYSTEM "limes.dtd">
<LIMES>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
      <LABEL>rdf</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
      <LABEL>foaf</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://purl.org/collections/nl/am/</NAMESPACE>
      <LABEL>am</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://purl.org/collections/nl/stadsarchief/</NAMESPACE>
      <LABEL>stads</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://purl.org/collections/nl/rijksmonumenten/</NAMESPACE>
      <LABEL>rmon</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
      <LABEL>owl</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
      <LABEL>rdfs</LABEL>
   </PREFIX>
   <SOURCE>
      <ID>source_a</ID>
      <ENDPOINT>http://semanticweb.cs.vu.nl/europeana/sparql/</ENDPOINT>
      <VAR>?a</VAR>
      <PAGESIZE>1000</PAGESIZE>
      <RESTRICTION>?a rdf:type stads:Person.</RESTRICTION>
      <PROPERTY>foaf:name AS lowercase</PROPERTY>
   </SOURCE>
   <TARGET>
      <ID>source_b</ID>
      <ENDPOINT>http://semanticweb.cs.vu.nl/europeana/sparql/</ENDPOINT>
      <VAR>?b</VAR>
      <PAGESIZE>1000</PAGESIZE>
      <RESTRICTION>?b rdf:type rmon:Person.</RESTRICTION>
      <PROPERTY>rdfs:label AS lowercase</PROPERTY>
   </TARGET>
   <METRIC>trigrams(a.foaf:name, b.rdfs:label)</METRIC>
   <ACCEPTANCE>
      <THRESHOLD>0.7</THRESHOLD>
      <FILE>accept.nt</FILE>
      <RELATION>owl:sameAs</RELATION>
   </ACCEPTANCE>
   <REVIEW>
      <THRESHOLD>0.7</THRESHOLD>
      <FILE>review.nt</FILE>
      <RELATION>owl:sameAs</RELATION>
   </REVIEW>
   <EXECUTION>Simple</EXECUTION>
   <OUTPUT>NT</OUTPUT>
</LIMES>
